### ISSUE TITLE
npm run start cannot load `chrome.browserAction.onClicked`

### ISSUE THREAD

**Issue by zhaofeng-shu33** [Harry-Chen/thu-learn-lib#1]

**Comment by Harry-Chen** [comment]
`npm start` 得到的文件应该被 Chrome 作为 Extension 加载，`npm build` 得到的 JS 就能用 node 加载了。

**Comment by zhaofeng-shu33** [comment]
OK.

**Comment by Harry-Chen** [comment]
`npm started` is deprecated and now removed. Refer to README for more information.
