### ISSUE TITLE
A possible way to fetch better

### ISSUE THREAD

**Issue by mayeths** [Harry-Chen/thu-learn-lib#11]
Token 失效的时候自动尝试二次登陆可以减轻一些心智负担，我修改少量地方，实现了一下 Token 失效重新登录。如果觉得可以我再提个 PR

![Snipaste](https://user-images.githubusercontent.com/37110574/71185500-83de5600-22b6-11ea-8f35-e608cc530b8e.png)

改动为
- 在 `constructor` 里用高阶函数 `withReAuth` wrap 了一下原来的 `myfetch`，其他的成员函数基本不用变，但现在它们调用 `myfetch` 失败会自动重试一次
- 去掉了内部状态 `loggedIn`，从外面看纯一点，fetch 数据失败就是真失败，用起来很舒服
- `constructor` 追加了一个能返回账号密码的函数 `up: () => Promise<{username: string, password: string}>`，用在登录时调用得到账号密码
- `login` public 或者 private 都无所谓了，反正调用数据 `get....` 在失败的时候就会调用 `login`，外面已经不用管理 Auth 的状态了，提供 `up()` 就可以。

这么做有点 break change，但外面不用记 Token 失效时间，爽。有个问题是 `getAllContents` 里可能会重复 `login`，但这个解决起来不难。

<br/>

(javascirpt 里写 class，`this` 的绑定真蛋疼。。)

**Comment by Harry-Chen** [comment]
LGTM，欢迎 Pull Request！
不过需要 `up` 是为了什么呢？我觉得传入就确定应该也没问题。

**Comment by mayeths** [comment]
我刚开始想的就是直接传入，后来有了一些考虑，就换了这种方式 orz。

- 一是**安全**。我不够了解js的私有变量，但 Helper 想随时登录一次，账号密码保持在内存中不雅观。它们是烫手山芋，Helper 每次通过接口从安全的地方获取即可，用完赶紧扔。怎么保存密码比较安全，这对 Helper 来说不需要知道，Helper 只需要一个 Promise 就能完成它的任务。

- 二是**生命周期麻烦**。现在 `loginIn` 状态变量和 Helper 的生命周期紧密绑定在一起，`loginIn` 失效，Helper 就需要 login 来更新。其实可以认为前一个 Helper 生命到头，已经死了。
我们实现 Helper 自动登录一次，也需要维护账号密码。这样，账号密码也成 Helper 状态变量，不好。而且账号密码这种状态 Helper 维护不过来，它没有更新账号密码的能力，**如果账号密码更新，Helper 就必须死一次。** 不如给个接口就行，这样 Helper 的生命周期和任何变量无关，也能随时获取仓库中最新的账号密码，创建者根本不用维护 Helper。

BTW，我可以通过判断参数来不破坏现有的使用方法（大概）

**Comment by Harry-Chen** [comment]
安全上这样的确是更有利的，虽然其实目前的使用场景都不怎么关注安全性（比如大家自己用，或者我的 Learn-Helper 实际上也是本地存了密码的），改了感觉也挺好的不过就 breaking 了。
第二点其实我想到了，但是其实我就是每次重新构造的（逃）
有时间的话麻烦 PR 一个吧~

**Comment by Harry-Chen** [comment]
（期待一个下文）

**Comment by mayeths** [comment]
我之前考试完生了场病很久没看（本来计划考试完花三天写了），现在刚回到家安顿下来
打算在除夕之前PR，应该是可以的。看了下校外登录网络学堂有点问题，需要花点时间
顺利的话这几天就可以PR
抱歉啦

**Comment by robertying** [comment]
> 我之前考试完生了场病很久没看（本来计划考试完花三天写了），现在刚回到家安顿下来
> 打算在除夕之前PR，应该是可以的。看了下校外登录网络学堂有点问题，需要花点时间
> 顺利的话这几天就可以PR
> 抱歉啦

校外直接用 api 貌似是没有问题的。

**Comment by mayeths** [comment]
嗯，这个我知道，所以我觉得是我的姿势不对，排查ing

**Comment by Harry-Chen** [comment]
辛苦了！期待中

**Comment by Harry-Chen** [comment]
Fixed by #14
