### ISSUE TITLE
获取课程日历的一个建议

### ISSUE THREAD

**Issue by xalanq** [Harry-Chen/thu-learn-lib#17]
<https://zhjw.cic.tsinghua.edu.cn/jxmh_out.do?m=bks_jxrl_all&p_start_date=20200216&p_end_date=20200316&jsoncallback=no_such_method>

官方接口可能限制了返回的大小，当日期区间太大就会报错（就连 1 个月都会gg）

```
java.lang.IndexOutOfBoundsException: Index: 29, Size: 29
```

看起来是将返回的数组大小限制到了 29 天。

因此建议在这个地方 <https://github.com/Harry-Chen/thu-learn-lib/blob/master/src/index.ts#L107> 对参数起始区间限制一下，或者将时间区间拆分成多个时间，然后合并一下。或者在文档里说明一下，让上游的 app 自己来搞。

**Comment by robertying** [comment]
https://github.com/robertying/learnX/blob/acf86823018d5e37a60bf1fb29bdf087d5f6c058/src/helpers/calendar.ts#L153

当时考虑到了这个问题，难道学校又改限制了吗？😅

**Comment by Harry-Chen** [comment]
Fixed by https://github.com/Harry-Chen/thu-learn-lib/commit/f7e3f234949a994985c1eac47aaa61684613e284

**Comment by panda2134** [comment]
我觉得应该是这个api没有考虑2月29号

**Comment by panda2134** [comment]
这个应该不是thu-learn-lib可以解决的
