### ISSUE TITLE
TEACHER模式下，一部分json数据的类型/处理方式不正确

### ISSUE THREAD

**Issue by MashPlant** [Harry-Chen/thu-learn-lib#22]
我发现了几个，不一定完整，也不一定会导致实际的问题，毕竟ts是编译到js执行的，所以一些类型错误可能在多数使用场景下被掩盖了。以下除了4，描述的都是TEACHER模式下的结果：
1.  `Course`: `kxh`是字符串，但它被赋值给了`ICourseInfo.courseIndex: number`字段
2. `Notification`: `sfqd`是数字，但是把`sfqd === '1'`的结果赋值给了`INotification.markedImportant`字段，这将导致它永远是`false`
3. `Notification`: 附件名称在STUDENT模式下在`fjmc`中，在TEACHER模式下在`fjbt`中，而代码中没有考虑`fjbt`，这将导致永远认为没有附件
4. (这个在所有模式下都有)`Notification`: 对于空的公告，`ggnr`可能为null而非空字符串，而js-base64的实现中，传入null似乎是按照字符串`'null'`来decode的，这会返回一个乱码

**Comment by Harry-Chen** [comment]
不如PR一个？

**Comment by MashPlant** [comment]
> 不如PR一个？

可以的，只是我其实根本不会写ts，环境也没有搭好，写完之后请您多多检阅。

**Comment by Harry-Chen** [comment]
Merged #23
