### ISSUE TITLE
Need some work to be used in Node.JS

### ISSUE THREAD

**Issue by jiegec** [Harry-Chen/thu-learn-lib#24]
It's not working under NodeJS since v2.0.0

See https://stackoverflow.com/questions/61305578/what-typescript-configuration-produces-output-closest-to-node-js-14-capabilities/61305579#61305579 https://github.com/dandv/typescript-modern-project#import-your-own-modules-without-specifying-an-extension

**Comment by jiegec** [comment]
After some investigation, using ESModules in NodeJS is not an easy job. I might need to migrate jiegec/clone-learn-tsinghua to TypeScript to use it.

**Comment by jiegec** [comment]
This is a total mess.

**Comment by jiegec** [comment]
I used webpack to solve the problem.

**Comment by Harry-Chen** [comment]
是不是还是用 commonJS 能解决这个问题
