### ISSUE TITLE
「管理忽略项」重置时，课程讨论一列没刷新。

### ISSUE THREAD

**Issue by Konano** [Harry-Chen/thu-learn-lib#6]
![image](https://user-images.githubusercontent.com/22500116/54580401-ddbda100-4a42-11e9-9a2e-fb15f5d191d2.png)

**Comment by Harry-Chen** [comment]
This issue belongs to xxr3376/Learn-Project

**Comment by Harry-Chen** [comment]
fixed by https://github.com/xxr3376/Learn-Project/commit/c50309156a94c8dbcc69b5410996299df5d88c36
