### ISSUE TITLE
How about a React Native app?

### ISSUE THREAD

**Issue by robertying** [Harry-Chen/thu-learn-lib#7]
Thanks for providing this awesome library!

Since it’s in TypeScript, why not make a React Native port using this lib? :p

It may only need a few modifications to remove Node specific tools and can be migrated to React Native.

I can have a try and would like to know your thoughts.

**Comment by robertying** [comment]
https://github.com/robertying/learnX

**Comment by Harry-Chen** [comment]
Wow it is really amazing!
